
name: Publish to GitHub Pages

# Run when the main branch is pushed
on:
  push:
    branches:
      - main
  workflow_run:
    workflows:
      - Fetch leaderboard
    branches:
      - main
    types:
      - completed

# Jobs
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:

      - uses: actions/checkout@v2
        with:
          submodules: true # To install themes
          fetch-depth: 0 # We need all history for .GitInfo and .Lastmod

      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: America/New_York

      # Set up Node.js and install dependencies
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: actions/cache@v1
        env:
          cache-version: v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-version }}-
            ${{ runner.os }}-
      - run: npm install

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.83.1"
          extended: true

      - name: Build
        run: hugo --minify --environment production

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.DEPLOY_KEY }}
          user_name: 'RowBot'
          user_email: '48598026+rowanbot@users.noreply.github.com'
          publish_dir: ./build
          publish_branch: build
          cname: crossword.rowanmanning.com
